  CREATE TABLE UGYFEL 
   (	AZON NUMBER NOT NULL ENABLE, 
	NEV VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	TELEFONSZAM VARCHAR2(255 CHAR), 
	EMAIL VARCHAR2(255 CHAR), 
	LAKCIM VARCHAR2(255 CHAR), 
	MEGKERESES NUMBER DEFAULT 0, 
	SZAZON NUMBER DEFAULT 0
   ) ;
